blank_issues_enabled: false
contact_links:
  - name: 📧 Email
    url: mailto:game.developer.mb@gmail.com
    about: Best for private or detailed communication.
  - name: 💬 Telegram
    url: https://t.me/IIMehrdadII
    about: Best for quick messages.
  - name: 🔗 LinkedIn
    url: https://www.linkedin.com/in/mehrdad-mb-658520232
    about: Best for professional networking.
